### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [226]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [227]:
a = torch.tensor(2)
a

tensor(2)

In [228]:
b = torch.tensor(3)
a * b

tensor(6)

### Convert a tensor to scalar

In [229]:
c = b.item()
c

3

### Creating 2D tensor

In [230]:
A = torch.tensor([[1, 2], [5, 6]])
A

tensor([[1, 2],
        [5, 6]])

## Tensor and Numpy

### Convert from tensor to numpy array

In [231]:
B = A.numpy()
B

array([[1, 2],
       [5, 6]])

### Convert from numpy array to tensor

In [232]:
C = torch.from_numpy(B)
C

tensor([[1, 2],
        [5, 6]])

## PyTorch and GPU

check if GPU is available

In [233]:
torch.cuda.is_available()

True

In [234]:
C.device

device(type='cpu')

In [235]:
D = C.cuda()
D

tensor([[1, 2],
        [5, 6]], device='cuda:0')

In [236]:
D.device

device(type='cuda', index=0)

In [237]:
# D.numpy()
E = D.cpu().numpy()
E

array([[1, 2],
       [5, 6]])

C  อยู่ใน CPU
D  อยู่ใน GPU

## Basic operations

In [238]:
D * 2

tensor([[ 2,  4],
        [10, 12]], device='cuda:0')

In [239]:
D - 2

tensor([[-1,  0],
        [ 3,  4]], device='cuda:0')

In [240]:
D.cpu() * np.array([1, 2])

/tmp/ipython-input-4124694458.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  D.cpu() * np.array([1, 2])


tensor([[ 1,  4],
        [ 5, 12]])

### Matrix multiplication

In [241]:
A = torch.tensor([[4, 5], [8, 9]])
B = torch.tensor([[1, 4], [7, 8]])

torch.matmul(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [242]:
torch.mm(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [243]:
A @ B

tensor([[ 39,  56],
        [ 71, 104]])

### Matrix transpose

ทรานสโคส สลับแนวทะแยง

In [244]:
A.t()

tensor([[4, 8],
        [5, 9]])

## Creating a specific type of tensor

In [245]:
a = torch.zeros(1, 2, 3)
a

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [246]:
b = torch.ones(1, 2, 3)
b

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [247]:
I = torch.eye(3)
I

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [248]:
R1 = torch.rand(2, 3)
R1

tensor([[0.4068, 0.4708, 0.2569],
        [0.8669, 0.8437, 0.2581]])

In [249]:
# ไกลจาก 0 จะมีโอกาสสุ่มน้อยลง
R2 = torch.randn(2, 3)
R2

tensor([[ 0.1183,  0.3763, -0.6848],
        [ 0.0427,  0.0571, -1.2196]])

In [250]:
a = torch.arange(6)
a

tensor([0, 1, 2, 3, 4, 5])

## Tensor's shape

### Checking the shape of a tensor

In [251]:
A.shape

torch.Size([2, 2])

In [252]:
A.size()

torch.Size([2, 2])

### Changing the shape of a tensor

In [253]:
u = torch.arange(6)
u.shape

torch.Size([6])

In [254]:
v = u.reshape(2, 3)

In [255]:
w = u.view(3, 2)
w

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [256]:
a =torch.arange(4)
b =torch.arange(4) +1
c = torch.stack([a, b], axis=0)
c

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4]])

In [257]:
d = torch.stack([a, b], axis=1)
d

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

In [258]:
# concatenate
e = torch.cat([a, b], axis=0)
e

tensor([0, 1, 2, 3, 1, 2, 3, 4])

In [259]:
# f = torch.cat([a, b], axis=1)
# f
# #เออเร่อเพราะมีแกน 0 ไม่มีแกน 1

### Squeezing a tensor (removing an extra dimension)

In [260]:
A = torch.zeros(1, 2, 3)
B = A.squeeze()
B
#หายไปแกนนึง(เหลือ 2 มิติ) ดูจาก []

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [261]:
B.shape

torch.Size([2, 3])

### Unsqueezing a tensor (adding an extra dimension)

In [262]:
# H.shape = (6, )
C = B.unsqueeze(axis=0)
C

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

## Indexing

In [263]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


In [264]:
P[[0, 1, 2], [0, 1, 2]]
P[0:3,0:3]


tensor([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10]])

In [265]:
torch.inverse(torch.tensor([[2.0, 0.0], [0.0, 5.0]]))

tensor([[0.5000, 0.0000],
        [0.0000, 0.2000]])

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [266]:
A ** 2

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [267]:
A.sum()

tensor(0.)

In [268]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


#1.

In [269]:
X = torch.randn(200, 7)
X.shape

torch.Size([200, 7])

In [270]:
b = torch.randn(8, 1)
b.shape

torch.Size([8, 1])

In [271]:
e = torch.randn(200, 1)
e.shape

torch.Size([200, 1])

#2.

In [272]:
a = torch.ones(200, 1)
a

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
      

#3

In [273]:
X = torch.cat([a, X], dim=1)
X

tensor([[ 1.0000, -1.1473,  0.2909,  ..., -0.7689,  0.1775, -0.2530],
        [ 1.0000,  0.8853,  0.4151,  ..., -1.6124,  0.4353,  0.6547],
        [ 1.0000, -0.1352,  1.0126,  ...,  0.1863,  1.8233, -1.0979],
        ...,
        [ 1.0000, -0.6908, -0.3747,  ...,  0.3183, -1.2196,  0.2032],
        [ 1.0000, -2.3619,  1.3556,  ..., -0.7420, -0.2732, -0.1219],
        [ 1.0000, -0.4138, -0.5121,  ...,  0.1849,  0.4233,  0.9461]])

#4

In [274]:
y = X @ b + e
y

tensor([[ 1.5639e+00],
        [-2.1656e+00],
        [ 2.0036e+00],
        [-3.6502e+00],
        [-2.5459e+00],
        [ 3.0304e+00],
        [ 1.5444e+00],
        [ 9.6100e-01],
        [ 5.6765e+00],
        [ 4.8299e+00],
        [-2.6200e+00],
        [-1.1844e+00],
        [ 2.5788e+00],
        [ 1.6267e+00],
        [ 4.3567e+00],
        [ 1.1780e+00],
        [ 8.5283e-01],
        [ 2.0802e+00],
        [-3.2122e+00],
        [-3.6169e+00],
        [-7.3866e-01],
        [ 9.7669e-01],
        [-5.4997e+00],
        [ 8.4399e-01],
        [ 2.9155e+00],
        [-1.0267e+00],
        [-3.1019e-01],
        [-3.4025e+00],
        [-1.6292e+00],
        [-8.4225e-01],
        [-9.0168e-01],
        [-5.6111e-02],
        [-4.2674e+00],
        [-8.8878e-01],
        [ 5.1003e+00],
        [-1.1293e+00],
        [ 5.9393e+00],
        [ 1.3470e+00],
        [-1.1977e+00],
        [ 9.4482e-01],
        [-4.3838e-01],
        [-7.6363e-01],
        [-3.3606e+00],
        [-4

#5

In [275]:
XX = X.T @ X
X_inv = torch.inverse(XX)
b_hat = X_inv @ X.T @ y
b_hat

tensor([[ 0.6158],
        [ 0.9238],
        [ 0.9697],
        [-1.5683],
        [ 1.0214],
        [ 0.4934],
        [ 0.2158],
        [-1.3786]])

#6

In [276]:
y_hat = X @ b_hat
y_hat

tensor([[ 1.4905],
        [-1.9515],
        [ 3.0367],
        [-3.7590],
        [-1.7363],
        [ 3.6684],
        [ 0.8444],
        [ 0.7979],
        [ 5.7759],
        [ 3.2964],
        [-1.5647],
        [-0.4502],
        [ 1.4784],
        [ 1.1737],
        [ 5.3164],
        [ 1.6796],
        [ 2.1107],
        [ 1.9142],
        [-2.0330],
        [-4.0662],
        [-0.5252],
        [ 2.6237],
        [-5.4993],
        [ 0.9336],
        [ 2.9904],
        [-1.4491],
        [-0.0985],
        [-2.8393],
        [-3.1415],
        [-2.0068],
        [ 0.1068],
        [ 0.2427],
        [-3.3872],
        [-1.9758],
        [ 6.0647],
        [ 0.1657],
        [ 5.5563],
        [ 1.6445],
        [-1.3630],
        [ 1.0873],
        [ 0.9530],
        [-0.2671],
        [-2.4124],
        [-4.3109],
        [ 3.6104],
        [ 3.1822],
        [ 7.4529],
        [ 4.8700],
        [-3.0271],
        [ 1.9894],
        [ 4.6256],
        [ 1.6831],
        [ 0.

#7

In [277]:
y = y.detach().numpy()
y_hat = y_hat.detach().numpy()

# mse = ((y - y_hat) ** 2).mean()
A = ((y - y_hat) ** 2)
mse = (1/200)* A.sum()
print("MSE =", mse)

MSE = 0.8446928
